"""Regenerate THIRD_PARTY_LICENSES.md from the installed environment.

The manifest was hand-maintained and had drifted: 16 of its 70 rows named a
version other than the one installed, including pypdfium2, and one row listed a
package version newer than the interpreter actually had. A license manifest
that is edited by hand is a claim about the dependency closure that nothing
checks, so this generates it instead, through the same resolver the compliance
gate uses.

Run:
  ./venv/bin/python tools/gen_third_party_licenses.py           # write
  ./venv/bin/python tools/gen_third_party_licenses.py --check   # verify only

`--check` exits non-zero when the file on disk does not match the environment,
so it can gate a release.
"""

from __future__ import annotations

import argparse
import importlib.metadata as m
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools import license_policy  # noqa: E402

HEADER = """# XLiteOCR — Third-Party License Manifest

Generated by `tools/gen_third_party_licenses.py` from the installed
environment. Do not edit by hand: run the generator, and use `--check` to
verify the file still matches what is installed.

Each row is resolved by `tools/license_policy.py`, which parses SPDX
expressions and falls back to exact classifier or legacy-string matches. It
never substring-matches, so a row saying MIT means the package's metadata
resolved to the MIT identifier and not merely that the letters appeared
somewhere. All entries are permissive or commercial-safe weak copyleft
(MPL-2.0). No GPL, AGPL or LGPL.

| Package | Version | Resolved licenses | Source |
|---|---|---|---|
"""


def classifiers(dist):
    return [c for c in (dist.metadata.get_all("Classifier") or []) if "License" in c]


def license_text(dist):
    lic = dist.metadata.get("License")
    return lic.splitlines()[0] if lic else ""


def build() -> str:
    rows = []
    unresolved = []
    for dist in m.distributions():
        name = (dist.metadata["Name"] or "").strip()
        if not name:
            continue
        try:
            version = dist.version
        except Exception:
            version = dist.metadata.get("Version") or "?"
        resolution = license_policy.resolve(
            name=name,
            version=version,
            license_expression=dist.metadata.get("License-Expression"),
            classifiers=classifiers(dist),
            license_text=license_text(dist),
        )
        ids = " / ".join(sorted(resolution.licenses)) or "UNRESOLVED"
        # Keep the source column short: the mechanism, not the whole string.
        source = resolution.source.split(" (")[0].replace("License-Expression", "SPDX")
        if source.startswith("Classifier"):
            source = "classifier"
        rows.append((name, version, ids, source))
        if not resolution.ok:
            unresolved.append(f"{name} {version}: {resolution.reason}")

    rows.sort(key=lambda r: r[0].lower())
    body = "".join(f"| {n} | {v} | {ids} | {src} |\n" for n, v, ids, src in rows)
    footer = f"\n_Total: {len(rows)} packages._\n"
    if unresolved:
        footer += (
            "\n> Unresolved entries below. The compliance gate fails while any\n"
            "> exist; they are listed rather than hidden.\n\n"
            + "".join(f"> - {u}\n" for u in unresolved)
        )
    return HEADER + body + footer


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file is out of date")
    args = parser.parse_args()

    target = Path(__file__).resolve().parent.parent / "THIRD_PARTY_LICENSES.md"
    generated = build()

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != generated:
            print(f"{target.name} is out of date; run tools/gen_third_party_licenses.py")
            return 1
        print(f"{target.name} matches the installed environment")
        return 0

    target.write_text(generated, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
