"""Regenerate THIRD_PARTY_LICENSES.md from the installed environment.

The manifest was hand-maintained and had drifted: 16 of its 70 rows named a
version other than the one installed, including pypdfium2, and one row listed a
package version newer than the interpreter actually had. A license manifest
that is edited by hand is a claim about the dependency closure that nothing
checks, so this generates it instead, through the same resolver the compliance
gate uses.

SCOPE: the PINNED closure, meaning every distribution named in
requirements.txt or constraints.txt, and nothing else. The first version of
this generator emitted every installed distribution, which made the file a
description of one virtualenv rather than of this project: a machine with a
different pytest picked up a different row, so `--check` failed everywhere
except the machine that generated it. Ambient test and packaging tooling is
not shipped and does not belong in a third-party manifest.

The license POLICY still covers everything installed. That check lives in
tests/test_compliance.py and is not narrowed by this scoping.

Run:
  ./venv/bin/python tools/gen_third_party_licenses.py           # write
  ./venv/bin/python tools/gen_third_party_licenses.py --check   # verify only

`--check` exits non-zero when the file on disk does not match the environment,
so it can gate a release.
"""

from __future__ import annotations

import argparse
import importlib.metadata as m
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools import license_policy  # noqa: E402

HEADER = """# XLiteOCR — Third-Party License Manifest

Generated by `tools/gen_third_party_licenses.py`. Do not edit by hand: run the
generator, and use `--check` to verify it still matches.

Scope is the pinned dependency closure, meaning every distribution named in
`requirements.txt` or `constraints.txt`. Test and packaging tooling that a
particular environment happens to carry is deliberately excluded: it is not
shipped, and including it would make this file describe one virtualenv rather
than this project. The license policy in `tests/test_compliance.py` still
applies to every installed distribution.

Each row is resolved by `tools/license_policy.py`, which parses SPDX
expressions and falls back to exact classifier or legacy-string matches. It
never substring-matches, so a row saying MIT means the package's metadata
resolved to the MIT identifier and not merely that the letters appeared
somewhere. All entries are permissive or commercial-safe weak copyleft
(MPL-2.0). No GPL, AGPL or LGPL.

| Package | Version | Resolved licenses | Source |
|---|---|---|---|
"""


def pinned_names() -> set:
    """Canonical names of every distribution this project pins."""
    from packaging.utils import canonicalize_name

    names = set()
    root = Path(__file__).resolve().parent.parent
    for filename in ("requirements.txt", "constraints.txt"):
        path = root / filename
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("-"):
                continue
            for sep in ("==", ">=", "<=", "~=", "!=", ">", "<", "="):
                if sep in line:
                    line = line.split(sep, 1)[0]
                    break
            line = line.split("[", 1)[0].strip()
            if line:
                names.add(canonicalize_name(line))
    return names


def classifiers(dist):
    return [c for c in (dist.metadata.get_all("Classifier") or []) if "License" in c]


def license_text(dist):
    lic = dist.metadata.get("License")
    return lic.splitlines()[0] if lic else ""


def build() -> str:
    from packaging.utils import canonicalize_name

    pinned = pinned_names()
    rows = []
    unresolved = []
    seen = set()
    for dist in m.distributions():
        name = (dist.metadata["Name"] or "").strip()
        if not name:
            continue
        canonical = canonicalize_name(name)
        if canonical not in pinned or canonical in seen:
            continue
        seen.add(canonical)
        try:
            version = dist.version
        except Exception:
            version = dist.metadata.get("Version") or "?"
        resolution = license_policy.resolve(
            name=name,
            version=version,
            license_expression=dist.metadata.get("License-Expression"),
            classifiers=classifiers(dist),
            license_text=license_text(dist),
        )
        ids = " / ".join(sorted(resolution.licenses)) or "UNRESOLVED"
        # Keep the source column short: the mechanism, not the whole string.
        source = resolution.source.split(" (")[0].replace("License-Expression", "SPDX")
        if source.startswith("Classifier"):
            source = "classifier"
        rows.append((name, version, ids, source))
        if not resolution.ok:
            unresolved.append(f"{name} {version}: {resolution.reason}")

    rows.sort(key=lambda r: r[0].lower())
    body = "".join(f"| {n} | {v} | {ids} | {src} |\n" for n, v, ids, src in rows)
    footer = f"\n_Total: {len(rows)} packages._\n"
    if unresolved:
        footer += (
            "\n> Unresolved entries below. The compliance gate fails while any\n"
            "> exist; they are listed rather than hidden.\n\n"
            + "".join(f"> - {u}\n" for u in unresolved)
        )
    return HEADER + body + footer


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file is out of date")
    args = parser.parse_args()

    target = Path(__file__).resolve().parent.parent / "THIRD_PARTY_LICENSES.md"
    generated = build()

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != generated:
            print(f"{target.name} is out of date; run tools/gen_third_party_licenses.py")
            return 1
        print(f"{target.name} matches the pinned closure")
        return 0

    target.write_text(generated, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
